# BoTorch Tutorials

The following information is summarised from the main BoTorch website.
https://botorch.org/docs/introduction.html

I have decided to summarise it to extract the core information from the documents to get started.


## Introduction to BoTorch

BoTorch is a library for Bayesian Optimisation research built on top of PyTorch. 

Bayesian Optimisation (BayesOpt) is an established technique for sequential optimisation of costly-to-evaluate black box functions. It can be applied to a wide variety of problems, including hyperparameter optimisation for machine learning algorithms, A/B testing, as well as many scientific and engineering problems.

## Why Botorch?

1. Improved Developer Efficiency
--> Modular and easily extensible interface for composing Bayesian Optimisation primitives (include probabilitic mdels, acquisition functions and optimisers).
--> Utilise quasi-Monte-Carlo acquisition functions

2. State-of-the-art Modelling
--> Provide support for state-of-the-art probabilisitc models in GPyTorch (Library for efficient, scalable Gaussian Process implemented in PyTorch).
--> Features include multi-task GPs, deep kernel learning, deep GPs, and approximate inference

3. Harnessing the features of PyTorch
--> Auto-differentiation, GPU implementations and dynamic computation graph 



# Simple Programme to get started

In [8]:
# ===============
# Install BoTorch
# ===============

# Via conda
# conda install botorch -c pytorch -c gpytorch

# Via pip
!pip install botorch

     |████████████████████████████████| 263 kB 4.1 MB/s eta 0:00:01
     |████████████████████████████████| 752.0 MB 10 kB/s s eta 0:00:01   |█▎                              | 30.2 MB 8.1 MB/s eta 0:01:30     |██▍                             | 56.1 MB 56.3 MB/s eta 0:00:13     |████▊                           | 111.3 MB 57.0 MB/s eta 0:00:12     |█████▋                          | 132.9 MB 42.3 MB/s eta 0:00:15     |███████▎                        | 171.0 MB 44.3 MB/s eta 0:00:14     |██████████████████              | 424.8 MB 30.9 MB/s eta 0:00:11     |███████████████████████████▏    | 638.3 MB 45.9 MB/s eta 0:00:03     |████████████████████████████▊   | 675.8 MB 43.0 MB/s eta 0:00:02     |█████████████████████████████▎  | 689.2 MB 43.0 MB/s eta 0:00:02     |█████████████████████████████▊  | 699.3 MB 31.5 MB/s eta 0:00:02
     |████████████████████████████████| 240 kB 29.6 MB/s eta 0:00:01
     |████████████████████████████████| 26.1 MB 33.4 MB/s eta 0:00:01
     |█████████████████████

In [ ]:
# ===============
# Fitting a Model
# ===============

import torch
from botorch.models import SingleTaskGP
from botorch.fit import fit_gpytorch_model
from botorch.utils import standardize
from gpytorch.mlls import ExactMarginalLogLikelihood


# Create training set
train_X = torch.rand(10,2)  # Create random matrix 10 rows x 2 columns
print("Training X \n\f\n", train_X)
Y = 1 - torch.norm(train_X-0.5,dim=-1,keepdim=True) # Generate Y
print("\nY\n\f\n", Y)
Y = Y + 0.1*torch.randn_like(Y)  # Add some noise
print("\nY with noise\n\f\n", Y)
train_Y = standardize(Y) # Stadardisation of Y for training

gp = SingleTaskGP(train_X,train_Y)
mll = ExactMarginalLogLikelihood(gp.likelihood,gp)
fit_gpytorch_model(mll)

Training X 

 tensor([[0.5450, 0.1751],
        [0.7470, 0.1939],
        [0.0198, 0.5851],
        [0.3032, 0.4526],
        [0.0116, 0.1795],
        [0.6036, 0.7312],
        [0.7514, 0.9459],
        [0.5687, 0.8204],
        [0.5119, 0.9591],
        [0.3701, 0.0635]])

Y

 tensor([[0.6720],
        [0.6067],
        [0.5123],
        [0.7975],
        [0.4158],
        [0.7466],
        [0.4881],
        [0.6723],
        [0.5407],
        [0.5446]])

Y with noise

 tensor([[0.5500],
        [0.6825],
        [0.6246],
        [0.9200],
        [0.4162],
        [0.8406],
        [0.4874],
        [0.5460],
        [0.5578],
        [0.6025]])
